#!/usr/bin/env node
/**
 * @file setup.ts
 * @description Interactive configuration wizard for the Daily News Digest.
 * Guides the user through setting up API keys, messenger credentials,
 * and optional scheduling. Writes a .env file upon completion.
 *
 * Usage:
 *   npx tsx setup.ts
 *   npm run setup
 */

import { createInterface } from 'readline';
import { writeFileSync, existsSync } from 'fs';
import { execSync, spawn } from 'child_process';
import { platform } from 'os';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface EnvVarEntry {
  key: string;
  description: string;
  required: boolean;
  default?: string;
}

type MessengerChoice = 'telegram' | 'discord' | 'email' | 'none';

// ---------------------------------------------------------------------------
// Readline helper
// ---------------------------------------------------------------------------

const rl = createInterface({ input: process.stdin, output: process.stdout });

function ask(question: string, defaultValue = ''): Promise<string> {
  return new Promise(resolve => {
    const hint = defaultValue ? ` [${defaultValue}]` : '';
    rl.question(`${question}${hint}: `, answer => {
      resolve(answer.trim() || defaultValue);
    });
  });
}

function askYesNo(question: string, defaultYes = true): Promise<boolean> {
  return new Promise(resolve => {
    const hint = defaultYes ? 'Y/n' : 'y/N';
    rl.question(`${question} [${hint}]: `, answer => {
      const trimmed = answer.trim().toLowerCase();
      if (trimmed === '') resolve(defaultYes);
      else resolve(trimmed === 'y' || trimmed === 'yes');
    });
  });
}

async function askMessenger(question: string): Promise<MessengerChoice> {
  const choices: MessengerChoice[] = ['telegram', 'discord', 'email', 'none'];
  const labels = ['Telegram', 'Discord', 'Email', 'None (console only)'];

  console.log(`\n${question}`);
  labels.forEach((c, i) => console.log(`  ${i + 1}. ${c}`));

  while (true) {
    const answer = await ask('Enter number');
    const idx = parseInt(answer, 10) - 1;
    if (idx >= 0 && idx < choices.length) return choices[idx];
    console.log(`  Please enter a number between 1 and ${choices.length}.`);
  }
}

// ---------------------------------------------------------------------------
// .env writer
// ---------------------------------------------------------------------------

// Schema of all known env vars — used for documentation/tooling purposes
export const ENV_SCHEMA: EnvVarEntry[] = [
  { key: 'ANTHROPIC_API_KEY', description: 'Anthropic API key',        required: true },
  { key: 'TELEGRAM_BOT_TOKEN', description: 'Telegram bot token',      required: false },
  { key: 'TELEGRAM_CHAT_ID',   description: 'Telegram chat ID',        required: false },
  { key: 'DISCORD_WEBHOOK_URL', description: 'Discord webhook URL',    required: false },
  { key: 'GMAIL_EMAIL',        description: 'Gmail address',           required: false },
  { key: 'GMAIL_PASSWORD',     description: 'Gmail app password',      required: false },
  { key: 'NEWS_TOPIC',         description: 'Default news topic',      required: false, default: 'Technology' },
  { key: 'ARTICLE_COUNT',      description: 'Articles per digest',     required: false, default: '5' },
  { key: 'SCHEDULE_HOUR',      description: 'Hour to run (0–23)',      required: false, default: '8' },
  { key: 'SCHEDULE_MINUTE',    description: 'Minute to run (0–59)',    required: false, default: '0' },
  { key: 'MESSENGER',          description: 'Default messenger',       required: false, default: 'none' },
];

function writeEnvFile(config: Record<string, string>, path = '.env'): void {
  const lines = [
    '# Daily News Digest – generated by setup.ts',
    '',
    '# Anthropic API',
    `ANTHROPIC_API_KEY=${config.ANTHROPIC_API_KEY}`,
    '',
    '# Messenger',
  ];

  if (config.TELEGRAM_BOT_TOKEN) {
    lines.push(`TELEGRAM_BOT_TOKEN=${config.TELEGRAM_BOT_TOKEN}`);
    lines.push(`TELEGRAM_CHAT_ID=${config.TELEGRAM_CHAT_ID}`);
  }
  if (config.DISCORD_WEBHOOK_URL) {
    lines.push(`DISCORD_WEBHOOK_URL=${config.DISCORD_WEBHOOK_URL}`);
  }
  if (config.GMAIL_EMAIL) {
    lines.push(`GMAIL_EMAIL=${config.GMAIL_EMAIL}`);
    lines.push(`GMAIL_PASSWORD=${config.GMAIL_PASSWORD}`);
  }

  lines.push('', '# Digest settings');
  lines.push(`NEWS_TOPIC=${config.NEWS_TOPIC}`);
  lines.push(`ARTICLE_COUNT=${config.ARTICLE_COUNT}`);
  lines.push('');

  writeFileSync(path, lines.join('\n'), 'utf8');
}

// ---------------------------------------------------------------------------
// Cron helper (Unix only)
// ---------------------------------------------------------------------------

function addCronJob(topic: string, messenger: string, hour: string): void {
  const cwd = process.cwd();
  const cronLine = `0 ${hour} * * * cd "${cwd}" && npx tsx digest.ts --topic "${topic}" --messenger ${messenger}`;

  try {
    let existing = '';
    try { existing = execSync('crontab -l 2>/dev/null', { encoding: 'utf8' }); } catch (_) {}

    if (existing.includes(cronLine)) {
      console.log('ℹ️   Cron job already exists – skipping.');
      return;
    }

    const updated = existing.trimEnd() + '\n' + cronLine + '\n';
    execSync(`echo ${JSON.stringify(updated)} | crontab -`);
    console.log(`✅  Cron job added: runs daily at ${hour}:00.`);
  } catch (err) {
    const e = err as { message: string };
    console.warn(`⚠️   Could not add cron job automatically: ${e.message}`);
    console.log('    Add this line manually with: crontab -e');
    console.log(`    ${cronLine}`);
  }
}

// ---------------------------------------------------------------------------
// Main wizard
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  console.log('\n' + '═'.repeat(55));
  console.log('  📰  Daily News Digest – Setup Wizard');
  console.log('═'.repeat(55));
  console.log('  This wizard will configure your news digest.');
  console.log('  Press Enter to accept the default value shown.\n');

  const config: Record<string, string> = {};

  // 1. Anthropic API key
  console.log('\n── Step 1/9: Anthropic API Key ─────────────────────');
  console.log('  Get yours at: https://console.anthropic.com/');
  config.ANTHROPIC_API_KEY = await ask('  Anthropic API key', process.env.ANTHROPIC_API_KEY || '');
  if (!config.ANTHROPIC_API_KEY) {
    console.error('❌  API key is required. Exiting.');
    rl.close();
    process.exit(1);
  }

  // 2. Messenger choice
  console.log('\n── Step 2/9: Messenger ──────────────────────────────');
  const messenger: MessengerChoice = await askMessenger('  Which messenger do you want to use?');
  config._messenger = messenger;

  // 3. Messenger credentials
  console.log('\n── Step 3/9: Messenger Credentials ─────────────────');
  if (messenger === 'telegram') {
    console.log('  Create a bot at: https://t.me/BotFather');
    config.TELEGRAM_BOT_TOKEN = await ask('  Telegram bot token');
    console.log('  To get your chat ID, send a message to your bot then visit:');
    console.log('  https://api.telegram.org/bot<TOKEN>/getUpdates');
    config.TELEGRAM_CHAT_ID = await ask('  Telegram chat ID');
  } else if (messenger === 'discord') {
    console.log('  Create a webhook in your Discord channel settings.');
    config.DISCORD_WEBHOOK_URL = await ask('  Discord webhook URL');
  } else if (messenger === 'email') {
    console.log('  Use an App Password, not your main Gmail password.');
    console.log('  Enable it at: myaccount.google.com → Security → App passwords');
    config.GMAIL_EMAIL    = await ask('  Gmail address');
    config.GMAIL_PASSWORD = await ask('  Gmail app password');
  } else {
    console.log('  Digests will be printed to the console.');
  }

  // 4. News topic
  console.log('\n── Step 4/9: News Topic ─────────────────────────────');
  config.NEWS_TOPIC = await ask('  Default news topic', 'Technology');

  // 5. Article count
  console.log('\n── Step 5/9: Article Count ──────────────────────────');
  config.ARTICLE_COUNT = await ask('  Articles per digest', '5');

  // 6. Daily time
  console.log('\n── Step 6/9: Daily Time ─────────────────────────────');
  const scheduleHour = await ask('  Hour to run daily (0–23)', '8');

  // 7. Install dependencies
  console.log('\n── Step 7/9: Dependencies ───────────────────────────');
  const shouldInstall = await askYesNo('  Install npm dependencies now?', true);

  // 8. Run test
  console.log('\n── Step 8/9: Test Run ───────────────────────────────');
  const shouldTest = await askYesNo('  Run a dry-run test after setup?', true);

  // 9. Cron job (Unix only)
  let shouldCron = false;
  if (platform() !== 'win32') {
    console.log('\n── Step 9/9: Cron Job ───────────────────────────────');
    shouldCron = await askYesNo('  Set up a daily cron job?', false);
  } else {
    console.log('\n── Step 9/9: Scheduling (Windows) ───────────────────');
    console.log('  Use scheduler.ts for automated scheduling on Windows:');
    console.log('    npx tsx scheduler.ts');
  }

  rl.close();

  // Write .env
  console.log('\n── Writing configuration ────────────────────────────');
  if (existsSync('.env')) {
    console.log('  ⚠️   Existing .env will be overwritten.');
  }
  writeEnvFile(config);
  console.log('  ✅  .env file created.');

  // Install dependencies
  if (shouldInstall) {
    console.log('\n── Installing dependencies ──────────────────────────');
    try {
      execSync('npm install', { stdio: 'inherit' });
      console.log('  ✅  Dependencies installed.');
    } catch (_) {
      console.error('  ❌  npm install failed. Run it manually: npm install');
    }
  }

  // Cron job
  if (shouldCron) {
    addCronJob(config.NEWS_TOPIC, config._messenger, scheduleHour);
  }

  // Summary
  console.log('\n' + '═'.repeat(55));
  console.log('  ✅  Setup complete!');
  console.log('═'.repeat(55));
  console.log(`  Topic    : ${config.NEWS_TOPIC}`);
  console.log(`  Articles : ${config.ARTICLE_COUNT}`);
  console.log(`  Delivery : ${config._messenger}`);
  console.log('');
  console.log('  Quick commands:');
  console.log('    npm test                                  # dry-run test');
  console.log(`    npx tsx digest.ts --topic "${config.NEWS_TOPIC}" --dry`);
  if (messenger !== 'none') {
    console.log(`    npx tsx digest.ts --messenger ${messenger}    # send now`);
  }
  console.log('    npx tsx scheduler.ts                      # run on schedule');
  console.log('═'.repeat(55) + '\n');

  // Test run
  if (shouldTest) {
    console.log('Running dry-run test…\n');
    const child = spawn('npx', ['tsx', 'digest.ts', '--topic', config.NEWS_TOPIC, '--dry'], {
      stdio: 'inherit',
      env: { ...process.env, ANTHROPIC_API_KEY: config.ANTHROPIC_API_KEY },
    });
    child.on('exit', (code: number | null) => {
      if (code === 0) console.log('\n✅  Test passed!');
      else console.error(`\n❌  Test exited with code ${code}.`);
    });
  }
}

main().catch(err => {
  const e = err as { message: string };
  console.error(`\n❌  Setup failed: ${e.message}`);
  rl.close();
  process.exit(1);
});
