I#!/usr/bin/env node
/**
 * @file setup.js
 * @description Interactive configuration wizard for the Daily News Digest.
 * Guides the user through setting up API keys, messenger credentials,
 * and optional scheduling. Writes a .env file upon completion.
 *
 * Usage:
 *   node setup.js
 *   npm run setup
 */

import { createInterface } from 'readline';
import { writeFileSync, existsSync } from 'fs';
import { execSync, spawn } from 'child_process';
import { platform } from 'os';

// ---------------------------------------------------------------------------
// Readline helper
// ---------------------------------------------------------------------------

const rl = createInterface({ input: process.stdin, output: process.stdout });

/**
 * Prompts the user with a question and returns their answer.
 *
 * @param {string} question - The prompt text shown to the user.
 * @param {string} [defaultValue=''] - Value used when the user presses Enter without typing.
 * @returns {Promise<string>}
 */
function ask(question, defaultValue = '') {
  return new Promise(resolve => {
    const hint = defaultValue ? ` [${defaultValue}]` : '';
    rl.question(`${question}${hint}: `, answer => {
      resolve(answer.trim() || defaultValue);
    });
  });
}

/**
 * Prompts for a yes/no answer.
 *
 * @param {string} question - The prompt text.
 * @param {boolean} [defaultYes=true] - Default if user just presses Enter.
 * @returns {Promise<boolean>}
 */
function askYesNo(question, defaultYes = true) {
  return new Promise(resolve => {
    const hint = defaultYes ? 'Y/n' : 'y/N';
    rl.question(`${question} [${hint}]: `, answer => {
      const trimmed = answer.trim().toLowerCase();
      if (trimmed === '') resolve(defaultYes);
      else resolve(trimmed === 'y' || trimmed === 'yes');
    });
  });
}

/**
 * Prompts the user to choose one item from a numbered list.
 *
 * @param {string} question - The prompt text.
 * @param {string[]} choices - Array of choice labels.
 * @returns {Promise<string>} The selected choice label (lowercase).
 */
async function askChoice(question, choices) {
  console.log(`\n${question}`);
  choices.forEach((c, i) => console.log(`  ${i + 1}. ${c}`));
  while (true) {
    const answer = await ask('Enter number');
    const idx = parseInt(answer, 10) - 1;
    if (idx >= 0 && idx < choices.length) return choices[idx].toLowerCase();
    console.log(`  Please enter a number between 1 and ${choices.length}.`);
  }
}

// ---------------------------------------------------------------------------
// .env writer
// ---------------------------------------------------------------------------

/**
 * Serialises a key→value config object into .env file format.
 *
 * @param {Record<string, string>} config - The config values to write.
 * @param {string} [path='.env'] - Output path.
 */
function writeEnvFile(config, path = '.env') {
  const lines = [
    '# Daily News Digest – generated by setup.js',
    '',
    '# Anthropic API',
    `ANTHROPIC_API_KEY=${config.ANTHROPIC_API_KEY}`,
    '',
    '# Messenger',
  ];

  if (config.TELEGRAM_BOT_TOKEN) {
    lines.push(`TELEGRAM_BOT_TOKEN=${config.TELEGRAM_BOT_TOKEN}`);
    lines.push(`TELEGRAM_CHAT_ID=${config.TELEGRAM_CHAT_ID}`);
  }
  if (config.DISCORD_WEBHOOK_URL) {
    lines.push(`DISCORD_WEBHOOK_URL=${config.DISCORD_WEBHOOK_URL}`);
  }
  if (config.GMAIL_EMAIL) {
    lines.push(`GMAIL_EMAIL=${config.GMAIL_EMAIL}`);
    lines.push(`GMAIL_PASSWORD=${config.GMAIL_PASSWORD}`);
  }

  lines.push('', '# Digest settings');
  lines.push(`NEWS_TOPIC=${config.NEWS_TOPIC}`);
  lines.push(`ARTICLE_COUNT=${config.ARTICLE_COUNT}`);
  lines.push('');

  writeFileSync(path, lines.join('\n'), 'utf8');
}

// ---------------------------------------------------------------------------
// Cron helper (Unix only)
// ---------------------------------------------------------------------------

/**
 * Attempts to add a cron job for daily digest delivery.
 * Only supported on Unix-like systems.
 *
 * @param {string} topic     - The news topic.
 * @param {string} messenger - The messenger (telegram/discord/email).
 * @param {string} hour      - Hour in 24h format (e.g. "8").
 */
function addCronJob(topic, messenger, hour) {
  const cwd = process.cwd();
  const cronLine = `0 ${hour} * * * cd "${cwd}" && node digest.js --topic "${topic}" --messenger ${messenger}`;

  try {
    let existing = '';
    try { existing = execSync('crontab -l 2>/dev/null', { encoding: 'utf8' }); } catch (_) {}

    if (existing.includes(cronLine)) {
      console.log('ℹ️   Cron job already exists – skipping.');
      return;
    }

    const updated = existing.trimEnd() + '\n' + cronLine + '\n';
    execSync(`echo ${JSON.stringify(updated)} | crontab -`);
    console.log(`✅  Cron job added: runs daily at ${hour}:00.`);
  } catch (err) {
    console.warn(`⚠️   Could not add cron job automatically: ${err.message}`);
    console.log(`    Add this line manually with: crontab -e`);
    console.log(`    ${cronLine}`);
  }
}

// ---------------------------------------------------------------------------
// Main wizard
// ---------------------------------------------------------------------------

async function main() {
  console.log('\n' + '═'.repeat(55));
  console.log('  📰  Daily News Digest – Setup Wizard');
  console.log('═'.repeat(55));
  console.log('  This wizard will configure your news digest.');
  console.log('  Press Enter to accept the default value shown.\n');

  const config = {};

  // 1. Anthropic API key
  console.log('\n── Step 1/9: Anthropic API Key ─────────────────────');
  console.log('  Get yours at: https://console.anthropic.com/');
  config.ANTHROPIC_API_KEY = await ask('  Anthropic API key', process.env.ANTHROPIC_API_KEY || '');
  if (!config.ANTHROPIC_API_KEY) {
    console.error('❌  API key is required. Exiting.');
    rl.close();
    process.exit(1);
  }

  // 2. Messenger choice
  console.log('\n── Step 2/9: Messenger ──────────────────────────────');
  const messenger = await askChoice('  Which messenger do you want to use?', ['Telegram', 'Discord', 'Email', 'None (console only)']);
  config._messenger = messenger.split(' ')[0].toLowerCase(); // 'telegram', 'discord', 'email', 'none'

  // 3. Messenger credentials
  console.log('\n── Step 3/9: Messenger Credentials ─────────────────');
  if (config._messenger === 'telegram') {
    console.log('  Create a bot at: https://t.me/BotFather');
    config.TELEGRAM_BOT_TOKEN = await ask('  Telegram bot token');
    console.log('  To get your chat ID, send a message to your bot then visit:');
    console.log('  https://api.telegram.org/bot<TOKEN>/getUpdates');
    config.TELEGRAM_CHAT_ID = await ask('  Telegram chat ID');
  } else if (config._messenger === 'discord') {
    console.log('  Create a webhook in your Discord channel settings.');
    config.DISCORD_WEBHOOK_URL = await ask('  Discord webhook URL');
  } else if (config._messenger === 'email') {
    console.log('  Use an App Password, not your main Gmail password.');
    console.log('  Enable it at: myaccount.google.com → Security → App passwords');
    config.GMAIL_EMAIL    = await ask('  Gmail address');
    config.GMAIL_PASSWORD = await ask('  Gmail app password');
  } else {
    console.log('  Digests will be printed to the console.');
  }

  // 4. News topic
  console.log('\n── Step 4/9: News Topic ─────────────────────────────');
  config.NEWS_TOPIC = await ask('  Default news topic', 'Technology');

  // 5. Article count
  console.log('\n── Step 5/9: Article Count ──────────────────────────');
  config.ARTICLE_COUNT = await ask('  Articles per digest', '5');

  // 6. Daily time
  console.log('\n── Step 6/9: Daily Time ─────────────────────────────');
  const scheduleHour = await ask('  Hour to run daily (0–23)', '8');

  // 7. Install dependencies
  console.log('\n── Step 7/9: Dependencies ───────────────────────────');
  const shouldInstall = await askYesNo('  Install npm dependencies now?', true);

  // 8. Run test
  console.log('\n── Step 8/9: Test Run ───────────────────────────────');
  const shouldTest = await askYesNo('  Run a dry-run test after setup?', true);

  // 9. Cron job (Unix only)
  let shouldCron = false;
  if (platform() !== 'win32') {
    console.log('\n── Step 9/9: Cron Job ───────────────────────────────');
    shouldCron = await askYesNo('  Set up a daily cron job?', false);
  } else {
    console.log('\n── Step 9/9: Scheduling (Windows) ───────────────────');
    console.log('  Use scheduler.js for automated scheduling on Windows:');
    console.log('    node scheduler.js');
  }

  rl.close();

  // Write .env
  console.log('\n── Writing configuration ────────────────────────────');
  if (existsSync('.env')) {
    console.log('  ⚠️   Existing .env will be overwritten.');
  }
  writeEnvFile(config);
  console.log('  ✅  .env file created.');

  // Install dependencies
  if (shouldInstall) {
    console.log('\n── Installing dependencies ──────────────────────────');
    try {
      execSync('npm install', { stdio: 'inherit' });
      console.log('  ✅  Dependencies installed.');
    } catch (err) {
      console.error('  ❌  npm install failed. Run it manually: npm install');
    }
  }

  // Cron job
  if (shouldCron) {
    addCronJob(config.NEWS_TOPIC, config._messenger, scheduleHour);
  }

  // Summary
  console.log('\n' + '═'.repeat(55));
  console.log('  ✅  Setup complete!');
  console.log('═'.repeat(55));
  console.log(`  Topic    : ${config.NEWS_TOPIC}`);
  console.log(`  Articles : ${config.ARTICLE_COUNT}`);
  console.log(`  Delivery : ${config._messenger}`);
  console.log('');
  console.log('  Quick commands:');
  console.log(`    npm test                               # dry-run test`);
  console.log(`    node digest.js --topic "${config.NEWS_TOPIC}" --dry`);
  if (config._messenger !== 'none') {
    console.log(`    node digest.js --messenger ${config._messenger}   # send now`);
  }
  console.log(`    node scheduler.js                      # run on schedule`);
  console.log('═'.repeat(55) + '\n');

  // Test run
  if (shouldTest) {
    console.log('Running dry-run test…\n');
    const child = spawn('node', ['digest.js', '--topic', config.NEWS_TOPIC, '--dry'], {
      stdio: 'inherit',
      env: { ...process.env, ANTHROPIC_API_KEY: config.ANTHROPIC_API_KEY },
    });
    child.on('exit', code => {
      if (code === 0) console.log('\n✅  Test passed!');
      else console.error(`\n❌  Test exited with code ${code}.`);
    });
  }
}

main().catch(err => {
  console.error(`\n❌  Setup failed: ${err.message}`);
  rl.close();
  process.exit(1);
});
